#!/bin/sh

case "$@" in
	# remove dir
	"/castor/cern.ch/user/s/stober/1")
	echo "/castor/cern.ch/user/s/stober/1: Is a directory" >&2
	exit 130;;
	# recursively remove dir
	"-r /castor/cern.ch/user/s/stober/1")
	exit 0;;
	# missing file
	"/castor/cern.ch/user/s/stober/123")
	echo "/castor/cern.ch/user/s/stober/123: No such file or directory" >&2
	exit 1;;
esac
exit -1
