#!/bin/sh

TIMELEFT="$(/bin/cat testfwk_timeleft 2> /dev/null)"
TIMELEFT=${TIMELEFT:-00:00:00}

/bin/cat << EOF
subject   : /C=DE/O=GermanGrid/OU=KIT/CN=Fred-Markus Stober/CN=proxy
issuer    : /C=DE/O=GermanGrid/OU=KIT/CN=Fred-Markus Stober
identity  : /C=DE/O=GermanGrid/OU=KIT/CN=Fred-Markus Stober
type      : proxy
strength  : 1024 bits
path      : /usr/users/stober/.globus/proxy.grid
timeleft  : $TIMELEFT
=== VO cms extension information ===
VO        : cms
subject   : /C=DE/O=GermanGrid/OU=KIT/CN=Fred-Markus Stober
issuer    : /DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch
attribute : /cms/dcms/Role=NULL/Capability=NULL
attribute : /cms/dbs/Role=NULL/Capability=NULL
attribute : /cms/Role=NULL/Capability=NULL
timeleft  : $TIMELEFT
uri       : lcg-voms.cern.ch:15002
EOF
exit 0
